apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        # envFrom:
        # - secretRef:
        #     name: msql-credentials
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: db-credentials
#   namespace: stg
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: secret-store
#   target:
#     name: msql-credentials
#     creationPolicy: Owner
#   data:
#   - secretKey: MYSQL_ROOT_PASSWORD
#     remoteRef:
#       key: db-credentials
#       version: AWSCURRENT
#       property: MYSQL_ROOT_PASSWORD
#   - secretKey: MYSQL_DATABASE
#     remoteRef:
#       key: db-credentials
#       version: AWSCURRENT
#       property: DB_NAME
#   - secretKey: MYSQL_USER
#     remoteRef:
#       key: db-credentials
#       version: AWSCURRENT
#       property: USER
#   - secretKey: MYSQL_PASSWORD
#     remoteRef:
#       key: db-credentials
#       version: AWSCURRENT
#       property: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  namespace: stg
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: stg
  name: wp-mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stg
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi