apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: stg
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: test-credentials
    creationPolicy: Owner
  data:
  - secretKey: WORDPRESS_DB_USER
    remoteRef:
      key: test-credentials
      version: AWSCURRENT
      property: USER
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: stg
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: msql-credentials
    creationPolicy: Owner
  data:
  - secretKey: WORDPRESS_DB_USER
    remoteRef:
      key: db-credentials
      version: AWSCURRENT
      property: USER
  - secretKey: WORDPRESS_DB_PASSWORD
    remoteRef:
      key: db-credentials
      version: AWSCURRENT
      property: PASSWORD
  - secretKey: WORDPRESS_DB_HOST
    remoteRef:
      key: db-credentials
      version: AWSCURRENT
      property: HOST