---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "wp-credentials,msql-credentials"
  name: wordpress
  namespace: stg
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress 
        envFrom:
        - secretRef:
            name: wp-credentials
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: stg
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: stg
  name: wp-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stg
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wp-credentials
  namespace: stg
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: wp-credentials
    creationPolicy: Owner
  data:
  - secretKey: WORDPRESS_DB_USER
    remoteRef:
      key: db-credentials
      version: AWSCURRENT
      property: USER
  - secretKey: WORDPRESS_DB_PASSWORD
    remoteRef:
      key: db-credentials
      version: AWSCURRENT
      property: PASSWORD
  - secretKey: WORDPRESS_DB_HOST
    remoteRef:
      key: db-credentials
      version: AWSCURRENT
      property: HOST
