apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexandrboicenco/external_secrets.git
    path: K8S/APP/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true